### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by mesca** [docEdub/csound-websocket-io-plugin#1]
Hi,

I'm trying to build your websocket plugin on macOS 14.5 (M2 chip), but I have errors. I tried both the main and dev branches with the latest Csound 6 and 7. Am I missing something? I would be grateful for any help you can offer.

```mkdir build && cd build && cmake .. && make```

With Csound 6 (master):
```
[ 20%] Building C object CMakeFiles/websocket-io.dir/src/_init_.c.o
[ 40%] Building C object CMakeFiles/websocket-io.dir/src/common.c.o
/(...)/csound-websocket-io-plugin/src/common.c:16:35: error: no member named 'GetHashTableValues' in 'struct CSOUND_'
    CONS_CELL *pathItem = csound->GetHashTableValues(csound, pathHashTable);
...
```

With Csound 7 (develop):
```
[ 20%] Building C object CMakeFiles/websocket-io.dir/src/_init_.c.o
/(...)/csound-websocket-io-plugin/src/_init_.c:8:10: error: field designator 'thread' does not refer to any field in type 'OENTRY' (aka 'struct oentry')
        .thread = 3,
         ^
/(...)/csound-websocket-io-plugin/src/_init_.c:11:10: error: field designator 'iopadr' does not refer to any field in type 'OENTRY' (aka 'struct oentry')
        .iopadr = (SUBR) websocket_get_init,
         ^
...
```

**Comment by docEdub** [comment]
Try the csound6 branch.

Also, FYI, I am not using this plugin for my own projects anymore, and I don't have the bandwidth to support it long-term.

I suspect the multithreading in this plugin is not done right. I've been having crashes and hanging in my Cabbage plugins that use it. I haven't proven that it's this plugin that's doing it, but the hanging makes me think there's a thread issue, which makes me suspect this plugin since it receives websocket messages on a separate thread that I tried to receive on the audio thread without blocking. This was my first attempt at doing something like this and it may not have been done right.

Feel free to fork it and maintain it yourself with whatever license you want, but be aware that it may be broken and I am not planning on fixing it or updating it for Csound 7 since I'm not using it anymore.

**Comment by mesca** [comment]
Thanks. I could build the plugin with the csound6 branch. Unfortunately, as it does not work with the latest stable and dev branches, I won't pursue further and will try other approaches.
